### ISSUE TITLE
msstyles

### ISSUE THREAD

**Issue by Beyond-Koma** [WildByDesign/Aero.msstyles-win32-darkmode#2]
Can you please help me with the theme file .msstyles Could you provide a detailed description or visual representation of the color, thickness, and exact location of the window pane lines, as shown in the image? Thank you!

https://i2.100024.xyz/2024/01/18/rew1mm.webp

**Comment by WildByDesign** [comment]
Unfortunately, I do not know where that resource is stored in the .msstyles file. Those theme files are quite complex and I only figured out how to change the one single resource to fix the issue related to win32-darkmode.
